### ISSUE TITLE
Consider adding Snow Fall 

### ISSUE THREAD

**Issue by technotarek** [wbkd/awesome-interactive-journalism#15]
Great compilation. I'd recommend you consider adding two canonical works. Snow Fall in particular was groundbreaking.

http://www.nytimes.com/projects/2012/snow-fall/?forceredirect=yes#/?part=tunnel-creek

https://www.theguardian.com/world/interactive/2013/may/26/firestorm-bushfire-dunalley-holmes-family

**Comment by chrtze** [comment]
How could I forget about Snowfall ;) Added it to the list.
